<?php
// $Id: georss.module,v 1.9.2.4 2009/09/22 18:49:57 rsoden Exp $

/**
 * @file
 * GeoRSS module to add geo data from CCK fields to the RSS feed
 */

/**
 * Implementation of hook_menu().
 */
function georss_menu() {
  $items = array();
  $items['admin/settings/georss'] = array(
    'title' => 'GeoRSS Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('georss_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer nodes'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function georss_theme() {
  return array(
    'georss_point' => array(),
  );
}

/**
 * GeoRSS settings form
 */
function georss_settings_form(&$form_state) {
  $settings = variable_get('georss_forms', array());
  $fields = content_fields();
  $options = array();
  foreach ($fields as $field) {
    $options[$field['field_name']] = $field['widget']['label'];
  }
  if (empty($options)) {
    drupal_set_message(t('To use the module, first you need to !createfields on the desired content-type to store latitude and longitude data.', array('!createfields' => l('create CCK fields', 'admin/content/types'))), 'warning');
  }

  $form = array();
  $form['georss_forms'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sources of Geo Data for RSS Feeds'),
    '#tree' => TRUE,
  );
  $form['georss_forms']['format'] = array(
    '#type' => 'select',
    '#title' => t('Format'),
    '#options' => array('simple' => t('GeoRSS-Simple'), 'gml' => t('GeoRSS-GML')),
    '#default_value' => isset($settings['format']) ? $settings['format'] : 'simple',
    );
  $form['georss_forms']['field_lat'] = array(
    '#type' => 'select',
    '#title' => t('Latitude'),
    '#options' => $options,
    '#default_value' => isset($settings['field_lat']) ? $settings['field_lat'] : '',
  );
  $form['georss_forms']['field_lon'] = array(
    '#type' => 'select',
    '#title' => t('Longitude'),
    '#options' => $options,
    '#default_value' => isset($settings['field_lon']) ? $settings['field_lon'] : '',
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi().
 */
function georss_nodeapi($node, $op) {
  switch ($op) {
    case 'rss item':
      $georss_settings = variable_get('georss_forms', FALSE);
      if ($georss_settings !== FALSE) {
        if (isset($node->$georss_settings['field_lat']) && isset($node->$georss_settings['field_lon'])) {
          $lon = $node->$georss_settings['field_lon'];
          $lat = $node->$georss_settings['field_lat'];
          if (!is_null($node->$georss_settings['field_lon']) && !is_null($node->$georss_settings['field_lat'])) {
            $items[] = theme_georss_point($lat['0']['value'], $lon['0']['value'], $georss_settings['format']);
          }

          unset($node->content[$georss_settings['field_lon']]);
          unset($node->content[$georss_settings['field_lat']]);

          return $items;
        }
      }
    break;
  }
}

/**
 * Theme GeoRSS points
 */
function theme_georss_point($lat, $lon, $format) {
  $output = array();
  switch ($format) {
    case 'gml':
      $output['key'] = 'georss:where';
      $output['namespace'] = array(
        'xmlns:georss' => 'http://www.georss.org/georss',
        'xmlns:gml' => 'http://www.opengis.net/gml'
      );
      $output['value'] = array(
        'gml:Point' => array(
          'gml:pos' => "$lat $lon"
        ),
      );
      break;
    case 'simple':
      $output['key'] = 'georss:point';
      $output['namespace'] = array('xmlns:georss' => 'http://www.georss.org/georss');
      $output['value'] = "$lat $lon";
    break;
  }
  return $output;
}